-- =============================================================================
-- Direktori Bengkel — Database Schema
-- Supabase PostgreSQL
-- =============================================================================

-- Drop existing tables if recreating (comment out in production)
-- drop table if exists reviews cascade;
-- drop table if exists places cascade;
-- drop table if exists categories cascade;

-- Categories
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  icon_name varchar(255)
);

-- Places
create table if not exists places (
  id bigint generated by default as identity primary key,
  category_id bigint not null references categories(id),
  name varchar(255) not null,
  address varchar(500),
  latitude numeric(10, 8) not null check (latitude between -90 and 90),
  longitude numeric(11, 8) not null check (longitude between -180 and 180),
  description text,
  phone varchar(20),
  opening_time time,
  closing_time time,
  photo_url varchar(500),
  rating numeric(3, 1) check (rating between 0 and 5),
  google_maps_url text,
  created_at timestamptz not null default now()
);

-- Reviews (opsional)
create table if not exists reviews (
  id bigint generated by default as identity primary key,
  place_id bigint not null references places(id) on delete cascade,
  user_id varchar(100) not null,
  rating numeric(3, 1) not null check (rating between 0 and 5),
  comment text,
  created_at timestamptz not null default now()
);
