create table if not exists categories (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  icon varchar(255)
);

create table if not exists places (
  id bigint generated by default as identity primary key,
  category_id bigint not null references categories(id),
  name varchar(255) not null,
  address varchar(500) not null,
  latitude numeric(10, 8) not null check (latitude between -90 and 90),
  longitude numeric(11, 8) not null check (longitude between -180 and 180),
  description text,
  phone varchar(20),
  opening_time time not null,
  closing_time time not null,
  photo_url varchar(500),
  rating numeric(3, 1) check (rating between 0 and 5),
  created_at timestamptz not null default now()
);

create table if not exists reviews (
  id bigint generated by default as identity primary key,
  place_id bigint not null references places(id) on delete cascade,
  user_id varchar(100) not null,
  rating numeric(3, 1) not null check (rating between 0 and 5),
  comment text,
  created_at timestamptz not null default now()
);
